export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTERED = 'USER_REGISTERED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
