export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTERED = 'USER_REGISTERED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';

export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const USER_AUTHORIZE = 'USER_AUTHORIZE';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
